### ISSUE TITLE
Prise en main de Laravel

### ISSUE THREAD

**Issue by jakysardoo** [it-akademy-students/intersession-2020-1-casseurs-codeurs#6]
Lien tuto : https://laracasts.com/skills/laravel
https://laravel.sillo.org/laravel-6-2/
Video Gamin : https://www.youtube.com/playlist?list=PLQOp2VdHrSRsIK67x9QMFeQmNzoiStJOz

**Comment by MohamedZogh** [comment]
Choix du tutoriel..

**Comment by jakysardoo** [comment]
https://laravel.sillo.org/laravel-6-2/
